# The name of your Worker. Alphanumeric values and dashes only.
name = "recordermoe"

# The entrypoint/path to the file that will be executed.
main = "./dist/worker.production.js"

# Whether you use `<NAME>.<SUBDOMAIN>.workers.dev` to
# test and deploy your Worker.
# @default `true`
workers_dev = false

# A date in the form yyyy-mm-dd, which will be used to determine
# which version of the Workers runtime is used.
compatibility_date = "2023-03-05"

[build]
command = "npm run-script build" 
