name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Worker
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Cloudflare Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
        env:
          DATABASE_SERVICE: ${{secrets.DATABASE_SERVICE}}
          COSMOS_KEY: ${{secrets.COSMOS_KEY}}
          COSMOS_ENDPOINT: ${{secrets.COSMOS_ENDPOINT}}
          COUCH_ENDPOINT: ${{secrets.COUCH_ENDPOINT}}
          BLOB_ENDPOINT_PUBLIC: ${{secrets.BLOB_ENDPOINT_PUBLIC}}